eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8903
spring:
    application:
        name: hystrix-dashboard-turbine
turbine:
    #\u5B9A\u4E49\u4E86\u8981\u76D1\u63A7\u7684\u670D\u52A1
    appConfig: service-feign, service-ribbon
    #\u6307\u5B9A\u805A\u5408\u54EA\u4E9B\u96C6\u7FA4\uFF0C\u591A\u4E2A\u4F7F\u7528\u201D,\u201D\u5206\u5272\uFF0C\u9ED8\u8BA4\u4E3Adefault
    aggregator:
        clusterConfig: default
      #\u6307\u5B9A\u96C6\u7FA4\u540D\u79F0
    clusterNameExpression: new String("default")