server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mzxlgx/springCloud.git
          searchPaths: config
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
